# Generated by Django 2.1.2 on 2018-11-05 05:25

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 11, 5, 5, 25, 27, 182019, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 11, 5, 5, 25, 27, 182064, tzinfo=utc))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 11, 5, 5, 25, 27, 184784, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 11, 5, 5, 25, 27, 184827, tzinfo=utc))),
            ],
            options={
                'db_table': 'moon_node_revision',
            },
        ),
        migrations.CreateModel(
            name='NodeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'moon_node_tag',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)])),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(6)])),
                ('role', models.CharField(choices=[(2, 2), (1, 1), (0, 0)], default=0, max_length=2)),
                ('logined_at', models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 5, 5, 25, 27, 179032, tzinfo=utc), null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 11, 5, 5, 25, 27, 179080, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 11, 5, 5, 25, 27, 179117, tzinfo=utc))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='moon_user_email_a6e5ab_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='moon_user_usernam_697c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='moon_user_role_e2234f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deleted_at'], name='moon_user_deleted_8bb123_idx'),
        ),
        migrations.AddField(
            model_name='tag',
            name='nodes',
            field=models.ManyToManyField(through='moon.NodeTag', to='moon.Node'),
        ),
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='moon.Tag'),
        ),
        migrations.AddField(
            model_name='nodetag',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moon.Node'),
        ),
        migrations.AddField(
            model_name='nodetag',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moon.Tag'),
        ),
        migrations.AddField(
            model_name='noderevision',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='moon.Node'),
        ),
        migrations.AddField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='moon.Node'),
        ),
        migrations.AddField(
            model_name='node',
            name='revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moon.Node'),
        ),
        migrations.AddField(
            model_name='node',
            name='tags',
            field=models.ManyToManyField(through='moon.NodeTag', to='moon.Tag'),
        ),
        migrations.AddField(
            model_name='node',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moon.User'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='moon_tag_name_1bc7ed_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['parent'], name='moon_tag_parent__3e45c1_idx'),
        ),
        migrations.AddIndex(
            model_name='nodetag',
            index=models.Index(fields=['node'], name='moon_node_t_node_id_5080e0_idx'),
        ),
        migrations.AddIndex(
            model_name='nodetag',
            index=models.Index(fields=['tag'], name='moon_node_t_tag_id_b33567_idx'),
        ),
        migrations.AddIndex(
            model_name='noderevision',
            index=models.Index(fields=['node'], name='moon_node_r_node_id_8a4f82_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['user'], name='moon_node_user_id_8f69fd_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['type'], name='moon_node_type_ecf8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['parent'], name='moon_node_parent__f2e9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['revision'], name='moon_node_revisio_f561ae_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['deleted_at'], name='moon_node_deleted_7fbd59_idx'),
        ),
    ]
